#!/bin/bash

# This script installs the project and its dependencies using uv.

# Exit immediately if a command exits with a non-zero status.
set -e

# Install the project in editable mode with the dev dependencies.
$HOME/.local/bin/uv pip install -e .[dev]